/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import './stencil.core';




export namespace Components {

  interface GtSentimeter {
    'themeColor': string;
  }
  interface GtSentimeterAttributes extends StencilHTMLAttributes {
    'themeColor'?: string;
  }
}

declare global {
  interface StencilElementInterfaces {
    'GtSentimeter': Components.GtSentimeter;
  }

  interface StencilIntrinsicElements {
    'gt-sentimeter': Components.GtSentimeterAttributes;
  }


  interface HTMLGtSentimeterElement extends Components.GtSentimeter, HTMLStencilElement {}
  var HTMLGtSentimeterElement: {
    prototype: HTMLGtSentimeterElement;
    new (): HTMLGtSentimeterElement;
  };

  interface HTMLElementTagNameMap {
    'gt-sentimeter': HTMLGtSentimeterElement
  }

  interface ElementTagNameMap {
    'gt-sentimeter': HTMLGtSentimeterElement;
  }


}
